# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frog_pcgp_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frog_dialog(object):
    def setupUi(self, frog_dialog):
        frog_dialog.setObjectName("frog_dialog")
        frog_dialog.resize(1475, 918)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/frog_image.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frog_dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(frog_dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(frog_dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.camera_image_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.camera_image_radiobutton.setChecked(True)
        self.camera_image_radiobutton.setObjectName("camera_image_radiobutton")
        self.horizontalLayout_2.addWidget(self.camera_image_radiobutton)
        self.loaded_image_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.loaded_image_radiobutton.setObjectName("loaded_image_radiobutton")
        self.horizontalLayout_2.addWidget(self.loaded_image_radiobutton)
        self.frog_image_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.frog_image_radiobutton.setObjectName("frog_image_radiobutton")
        self.horizontalLayout_2.addWidget(self.frog_image_radiobutton)
        self.bkg_image_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.bkg_image_radiobutton.setObjectName("bkg_image_radiobutton")
        self.horizontalLayout_2.addWidget(self.bkg_image_radiobutton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(frog_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.probe_material_table = QtWidgets.QTableWidget(self.tab)
        self.probe_material_table.setRowCount(5)
        self.probe_material_table.setColumnCount(2)
        self.probe_material_table.setObjectName("probe_material_table")
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probe_material_table.setItem(2, 1, item)
        self.gridLayout_2.addWidget(self.probe_material_table, 11, 1, 1, 1)
        self.gate_material_table = QtWidgets.QTableWidget(self.tab)
        self.gate_material_table.setRowCount(5)
        self.gate_material_table.setColumnCount(2)
        self.gate_material_table.setObjectName("gate_material_table")
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gate_material_table.setItem(2, 0, item)
        self.gridLayout_2.addWidget(self.gate_material_table, 12, 1, 1, 1)
        self.frog_geometry_combobox = QtWidgets.QComboBox(self.tab)
        self.frog_geometry_combobox.setObjectName("frog_geometry_combobox")
        self.gridLayout_2.addWidget(self.frog_geometry_combobox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 8, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frog_restart_button = QtWidgets.QPushButton(self.tab)
        self.frog_restart_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frog_restart_button.setObjectName("frog_restart_button")
        self.horizontalLayout_8.addWidget(self.frog_restart_button)
        self.frog_run_button = QtWidgets.QPushButton(self.tab)
        self.frog_run_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frog_run_button.setObjectName("frog_run_button")
        self.horizontalLayout_8.addWidget(self.frog_run_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.frog_iterations_spinbox = QtWidgets.QSpinBox(self.tab)
        self.frog_iterations_spinbox.setMaximum(1000)
        self.frog_iterations_spinbox.setProperty("value", 10)
        self.frog_iterations_spinbox.setObjectName("frog_iterations_spinbox")
        self.horizontalLayout_8.addWidget(self.frog_iterations_spinbox)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        self.frog_size_spinbox = QtWidgets.QSpinBox(self.tab)
        self.frog_size_spinbox.setMaximum(2048)
        self.frog_size_spinbox.setSingleStep(16)
        self.frog_size_spinbox.setProperty("value", 128)
        self.frog_size_spinbox.setObjectName("frog_size_spinbox")
        self.gridLayout_2.addWidget(self.frog_size_spinbox, 0, 1, 1, 1)
        self.frog_pulse_duration_label = QtWidgets.QLabel(self.tab)
        self.frog_pulse_duration_label.setObjectName("frog_pulse_duration_label")
        self.gridLayout_2.addWidget(self.frog_pulse_duration_label, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 11, 0, 1, 1)
        self.frog_dt_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.frog_dt_spinbox.setDecimals(1)
        self.frog_dt_spinbox.setMaximum(10000.0)
        self.frog_dt_spinbox.setProperty("value", 10.0)
        self.frog_dt_spinbox.setObjectName("frog_dt_spinbox")
        self.gridLayout_2.addWidget(self.frog_dt_spinbox, 1, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frog_error_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frog_error_label.sizePolicy().hasHeightForWidth())
        self.frog_error_label.setSizePolicy(sizePolicy)
        self.frog_error_label.setMinimumSize(QtCore.QSize(35, 0))
        self.frog_error_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.frog_error_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frog_error_label.setObjectName("frog_error_label")
        self.horizontalLayout_13.addWidget(self.frog_error_label)
        self.error_line_plot_widget = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_line_plot_widget.sizePolicy().hasHeightForWidth())
        self.error_line_plot_widget.setSizePolicy(sizePolicy)
        self.error_line_plot_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.error_line_plot_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.error_line_plot_widget.setObjectName("error_line_plot_widget")
        self.horizontalLayout_13.addWidget(self.error_line_plot_widget)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 6, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.tab)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_4.setObjectName("widget_4")
        self.frog_materials_enable_radiobutton = QtWidgets.QRadioButton(self.widget_4)
        self.frog_materials_enable_radiobutton.setGeometry(QtCore.QRect(10, 0, 240, 20))
        self.frog_materials_enable_radiobutton.setMinimumSize(QtCore.QSize(0, 20))
        self.frog_materials_enable_radiobutton.setChecked(True)
        self.frog_materials_enable_radiobutton.setObjectName("frog_materials_enable_radiobutton")
        self.gridLayout_2.addWidget(self.widget_4, 10, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 12, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_3.setObjectName("widget_3")
        self.auto_run_radiobutton = QtWidgets.QRadioButton(self.widget_3)
        self.auto_run_radiobutton.setGeometry(QtCore.QRect(10, 0, 240, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_run_radiobutton.sizePolicy().hasHeightForWidth())
        self.auto_run_radiobutton.setSizePolicy(sizePolicy)
        self.auto_run_radiobutton.setMinimumSize(QtCore.QSize(0, 10))
        self.auto_run_radiobutton.setObjectName("auto_run_radiobutton")
        self.gridLayout_2.addWidget(self.widget_3, 5, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 5, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.load_bkg_button = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_bkg_button.sizePolicy().hasHeightForWidth())
        self.load_bkg_button.setSizePolicy(sizePolicy)
        self.load_bkg_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_bkg_button.setObjectName("load_bkg_button")
        self.horizontalLayout_14.addWidget(self.load_bkg_button)
        self.bkg_image_filename_label = QtWidgets.QLabel(self.tab_2)
        self.bkg_image_filename_label.setText("")
        self.bkg_image_filename_label.setObjectName("bkg_image_filename_label")
        self.horizontalLayout_14.addWidget(self.bkg_image_filename_label)
        self.gridLayout.addLayout(self.horizontalLayout_14, 20, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.time_resolution_spinbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.time_resolution_spinbox.setProperty("value", 7.5)
        self.time_resolution_spinbox.setObjectName("time_resolution_spinbox")
        self.gridLayout.addWidget(self.time_resolution_spinbox, 14, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.roi_top_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.roi_top_spinbox.setMaximum(10000)
        self.roi_top_spinbox.setObjectName("roi_top_spinbox")
        self.horizontalLayout_5.addWidget(self.roi_top_spinbox)
        self.roi_left_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.roi_left_spinbox.setMaximum(10000)
        self.roi_left_spinbox.setObjectName("roi_left_spinbox")
        self.horizontalLayout_5.addWidget(self.roi_left_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 11, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setMinimumSize(QtCore.QSize(0, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 10, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.directory_lineedit = QtWidgets.QLineEdit(self.tab_2)
        self.directory_lineedit.setObjectName("directory_lineedit")
        self.horizontalLayout_3.addWidget(self.directory_lineedit)
        self.save_dir_button = QtWidgets.QPushButton(self.tab_2)
        self.save_dir_button.setMinimumSize(QtCore.QSize(20, 0))
        self.save_dir_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.save_dir_button.setObjectName("save_dir_button")
        self.horizontalLayout_3.addWidget(self.save_dir_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 14, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.camera_start_button = QtWidgets.QPushButton(self.tab_2)
        self.camera_start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_start_button.setObjectName("camera_start_button")
        self.horizontalLayout_4.addWidget(self.camera_start_button)
        self.camera_stop_button = QtWidgets.QPushButton(self.tab_2)
        self.camera_stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_stop_button.setObjectName("camera_stop_button")
        self.horizontalLayout_4.addWidget(self.camera_stop_button)
        self.camera_init_button = QtWidgets.QPushButton(self.tab_2)
        self.camera_init_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_init_button.setObjectName("camera_init_button")
        self.horizontalLayout_4.addWidget(self.camera_init_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.threshold_spinbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.threshold_spinbox.setDecimals(3)
        self.threshold_spinbox.setMaximum(1.0)
        self.threshold_spinbox.setSingleStep(0.025)
        self.threshold_spinbox.setProperty("value", 0.05)
        self.threshold_spinbox.setObjectName("threshold_spinbox")
        self.gridLayout.addWidget(self.threshold_spinbox, 17, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 16, 1, 1, 1)
        self.central_wavelength_spinbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.central_wavelength_spinbox.setMinimum(100.0)
        self.central_wavelength_spinbox.setMaximum(1500.0)
        self.central_wavelength_spinbox.setProperty("value", 782.0)
        self.central_wavelength_spinbox.setObjectName("central_wavelength_spinbox")
        self.gridLayout.addWidget(self.central_wavelength_spinbox, 15, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 0, 1, 1)
        self.bkg_subtract_radiobutton = QtWidgets.QRadioButton(self.tab_2)
        self.bkg_subtract_radiobutton.setChecked(True)
        self.bkg_subtract_radiobutton.setObjectName("bkg_subtract_radiobutton")
        self.gridLayout.addWidget(self.bkg_subtract_radiobutton, 18, 1, 1, 1)
        self.save_image_button = QtWidgets.QPushButton(self.tab_2)
        self.save_image_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.save_image_button.setObjectName("save_image_button")
        self.gridLayout.addWidget(self.save_image_button, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 15, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.camera_bkg_button = QtWidgets.QPushButton(self.tab_2)
        self.camera_bkg_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camera_bkg_button.setObjectName("camera_bkg_button")
        self.horizontalLayout_7.addWidget(self.camera_bkg_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 19, 1, 1, 1)
        self.dispersion_spinbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.dispersion_spinbox.setDecimals(3)
        self.dispersion_spinbox.setProperty("value", 0.34)
        self.dispersion_spinbox.setObjectName("dispersion_spinbox")
        self.gridLayout.addWidget(self.dispersion_spinbox, 13, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 1, 1, 1)
        self.camera_state_label = QtWidgets.QLabel(self.tab_2)
        self.camera_state_label.setObjectName("camera_state_label")
        self.gridLayout.addWidget(self.camera_state_label, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 18, 0, 1, 1)
        self.save_name_lineedit = QtWidgets.QLineEdit(self.tab_2)
        self.save_name_lineedit.setObjectName("save_name_lineedit")
        self.gridLayout.addWidget(self.save_name_lineedit, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 19, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roi_width_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.roi_width_spinbox.setMinimum(1)
        self.roi_width_spinbox.setMaximum(10000)
        self.roi_width_spinbox.setProperty("value", 200)
        self.roi_width_spinbox.setObjectName("roi_width_spinbox")
        self.horizontalLayout_6.addWidget(self.roi_width_spinbox)
        self.roi_height_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.roi_height_spinbox.setMinimum(1)
        self.roi_height_spinbox.setMaximum(10000)
        self.roi_height_spinbox.setProperty("value", 200)
        self.roi_height_spinbox.setObjectName("roi_height_spinbox")
        self.horizontalLayout_6.addWidget(self.roi_height_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 12, 1, 1, 1)
        self.camera_name_lineedit = QtWidgets.QLineEdit(self.tab_2)
        self.camera_name_lineedit.setObjectName("camera_name_lineedit")
        self.gridLayout.addWidget(self.camera_name_lineedit, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 17, 0, 1, 1)
        self.camera_framecounter_label = QtWidgets.QLabel(self.tab_2)
        self.camera_framecounter_label.setObjectName("camera_framecounter_label")
        self.gridLayout.addWidget(self.camera_framecounter_label, 4, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.load_button = QtWidgets.QPushButton(self.tab_2)
        self.load_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_12.addWidget(self.load_button)
        self.load_filename_label = QtWidgets.QLabel(self.tab_2)
        self.load_filename_label.setObjectName("load_filename_label")
        self.horizontalLayout_12.addWidget(self.load_filename_label)
        self.gridLayout.addLayout(self.horizontalLayout_12, 7, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.camera_gain_spinbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.camera_gain_spinbox.setMinimum(-100.0)
        self.camera_gain_spinbox.setMaximum(1000.0)
        self.camera_gain_spinbox.setObjectName("camera_gain_spinbox")
        self.horizontalLayout_15.addWidget(self.camera_gain_spinbox)
        self.camera_gain_label = QtWidgets.QLabel(self.tab_2)
        self.camera_gain_label.setObjectName("camera_gain_label")
        self.horizontalLayout_15.addWidget(self.camera_gain_label)
        self.gridLayout.addLayout(self.horizontalLayout_15, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.status_label = QtWidgets.QLabel(frog_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.vertical_splitter = QtWidgets.QSplitter(frog_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertical_splitter.sizePolicy().hasHeightForWidth())
        self.vertical_splitter.setSizePolicy(sizePolicy)
        self.vertical_splitter.setOrientation(QtCore.Qt.Vertical)
        self.vertical_splitter.setObjectName("vertical_splitter")
        self.horizontal_splitter = QtWidgets.QSplitter(self.vertical_splitter)
        self.horizontal_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_splitter.setObjectName("horizontal_splitter")
        self.primary_image_widget2 = QtWidgets.QWidget(self.horizontal_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primary_image_widget2.sizePolicy().hasHeightForWidth())
        self.primary_image_widget2.setSizePolicy(sizePolicy)
        self.primary_image_widget2.setObjectName("primary_image_widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.primary_image_widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.primary_image_label = QtWidgets.QLabel(self.primary_image_widget2)
        self.primary_image_label.setObjectName("primary_image_label")
        self.verticalLayout_5.addWidget(self.primary_image_label)
        self.primary_image_widget = ImageView(self.primary_image_widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primary_image_widget.sizePolicy().hasHeightForWidth())
        self.primary_image_widget.setSizePolicy(sizePolicy)
        self.primary_image_widget.setObjectName("primary_image_widget")
        self.verticalLayout_5.addWidget(self.primary_image_widget)
        self.secondary_image_widget2 = QtWidgets.QWidget(self.horizontal_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondary_image_widget2.sizePolicy().hasHeightForWidth())
        self.secondary_image_widget2.setSizePolicy(sizePolicy)
        self.secondary_image_widget2.setObjectName("secondary_image_widget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.secondary_image_widget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.secondary_image_label = QtWidgets.QLabel(self.secondary_image_widget2)
        self.secondary_image_label.setObjectName("secondary_image_label")
        self.verticalLayout_6.addWidget(self.secondary_image_label)
        self.secondary_image_widget = ImageView(self.secondary_image_widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondary_image_widget.sizePolicy().hasHeightForWidth())
        self.secondary_image_widget.setSizePolicy(sizePolicy)
        self.secondary_image_widget.setObjectName("secondary_image_widget")
        self.verticalLayout_6.addWidget(self.secondary_image_widget)
        self.line_plot_widget_container = QtWidgets.QWidget(self.vertical_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_plot_widget_container.sizePolicy().hasHeightForWidth())
        self.line_plot_widget_container.setSizePolicy(sizePolicy)
        self.line_plot_widget_container.setObjectName("line_plot_widget_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.line_plot_widget_container)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.line_plot_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.line_plot_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.line_plot_widget = PlotWidget(self.line_plot_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_plot_widget.sizePolicy().hasHeightForWidth())
        self.line_plot_widget.setSizePolicy(sizePolicy)
        self.line_plot_widget.setObjectName("line_plot_widget")
        self.verticalLayout_9.addWidget(self.line_plot_widget)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.line_plot_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.line_plot_widget2 = PlotWidget(self.line_plot_widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_plot_widget2.sizePolicy().hasHeightForWidth())
        self.line_plot_widget2.setSizePolicy(sizePolicy)
        self.line_plot_widget2.setObjectName("line_plot_widget2")
        self.verticalLayout_8.addWidget(self.line_plot_widget2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addWidget(self.vertical_splitter)

        self.retranslateUi(frog_dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frog_dialog)

    def retranslateUi(self, frog_dialog):
        _translate = QtCore.QCoreApplication.translate
        frog_dialog.setWindowTitle(_translate("frog_dialog", "FROG"))
        self.camera_image_radiobutton.setText(_translate("frog_dialog", "Camera"))
        self.loaded_image_radiobutton.setText(_translate("frog_dialog", "Loaded image"))
        self.frog_image_radiobutton.setText(_translate("frog_dialog", "FROG"))
        self.bkg_image_radiobutton.setText(_translate("frog_dialog", "Background"))
        item = self.probe_material_table.horizontalHeaderItem(0)
        item.setText(_translate("frog_dialog", "Material"))
        item = self.probe_material_table.horizontalHeaderItem(1)
        item.setText(_translate("frog_dialog", "Thickness"))
        __sortingEnabled = self.probe_material_table.isSortingEnabled()
        self.probe_material_table.setSortingEnabled(False)
        item = self.probe_material_table.item(0, 0)
        item.setText(_translate("frog_dialog", "caco3_e"))
        item = self.probe_material_table.item(0, 1)
        item.setText(_translate("frog_dialog", "13.7"))
        item = self.probe_material_table.item(1, 0)
        item.setText(_translate("frog_dialog", "bk7"))
        item = self.probe_material_table.item(1, 1)
        item.setText(_translate("frog_dialog", "12"))
        item = self.probe_material_table.item(2, 0)
        item.setText(_translate("frog_dialog", "air"))
        item = self.probe_material_table.item(2, 1)
        item.setText(_translate("frog_dialog", "0"))
        self.probe_material_table.setSortingEnabled(__sortingEnabled)
        item = self.gate_material_table.horizontalHeaderItem(0)
        item.setText(_translate("frog_dialog", "Material"))
        item = self.gate_material_table.horizontalHeaderItem(1)
        item.setText(_translate("frog_dialog", "Thickness"))
        __sortingEnabled = self.gate_material_table.isSortingEnabled()
        self.gate_material_table.setSortingEnabled(False)
        item = self.gate_material_table.item(0, 0)
        item.setText(_translate("frog_dialog", "bk7"))
        item = self.gate_material_table.item(0, 1)
        item.setText(_translate("frog_dialog", "6"))
        item = self.gate_material_table.item(1, 0)
        item.setText(_translate("frog_dialog", "fs"))
        item = self.gate_material_table.item(1, 1)
        item.setText(_translate("frog_dialog", "2"))
        self.gate_material_table.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("frog_dialog", "dt"))
        self.label_22.setText(_translate("frog_dialog", "Pulse duration"))
        self.label_20.setText(_translate("frog_dialog", "Enable materials"))
        self.frog_restart_button.setText(_translate("frog_dialog", "Restart"))
        self.frog_run_button.setText(_translate("frog_dialog", "Run"))
        self.label_18.setText(_translate("frog_dialog", "iterations"))
        self.frog_pulse_duration_label.setText(_translate("frog_dialog", "--"))
        self.label_5.setText(_translate("frog_dialog", "Size"))
        self.label_23.setText(_translate("frog_dialog", "Probe material"))
        self.frog_dt_spinbox.setSuffix(_translate("frog_dialog", " fs"))
        self.frog_error_label.setText(_translate("frog_dialog", "--"))
        self.label_19.setText(_translate("frog_dialog", "Error"))
        self.frog_materials_enable_radiobutton.setText(_translate("frog_dialog", "Materials enabled"))
        self.label_26.setText(_translate("frog_dialog", "Geometry"))
        self.label_24.setText(_translate("frog_dialog", "Gate material"))
        self.auto_run_radiobutton.setText(_translate("frog_dialog", "Auto run"))
        self.label_28.setText(_translate("frog_dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frog_dialog", "FROG"))
        self.label_4.setText(_translate("frog_dialog", "Directory"))
        self.load_bkg_button.setText(_translate("frog_dialog", "Load bkg"))
        self.label.setText(_translate("frog_dialog", "Camera name"))
        self.label_6.setText(_translate("frog_dialog", "Gain"))
        self.time_resolution_spinbox.setSuffix(_translate("frog_dialog", " fs/px"))
        self.label_12.setText(_translate("frog_dialog", "Dispersion"))
        self.directory_lineedit.setText(_translate("frog_dialog", "./data"))
        self.save_dir_button.setText(_translate("frog_dialog", "..."))
        self.label_13.setText(_translate("frog_dialog", "Time resolution"))
        self.camera_start_button.setText(_translate("frog_dialog", "Start"))
        self.camera_stop_button.setText(_translate("frog_dialog", "Stop"))
        self.camera_init_button.setText(_translate("frog_dialog", "Init"))
        self.label_8.setText(_translate("frog_dialog", "Frame counter"))
        self.label_2.setText(_translate("frog_dialog", "Load image"))
        self.label_7.setText(_translate("frog_dialog", "State"))
        self.label_10.setText(_translate("frog_dialog", "ROI top / left"))
        self.central_wavelength_spinbox.setSuffix(_translate("frog_dialog", " nm"))
        self.label_3.setText(_translate("frog_dialog", "Save name"))
        self.label_11.setText(_translate("frog_dialog", "ROI w / h"))
        self.bkg_subtract_radiobutton.setText(_translate("frog_dialog", "Background subtract"))
        self.save_image_button.setText(_translate("frog_dialog", "Save"))
        self.label_14.setText(_translate("frog_dialog", "Central wavelength"))
        self.camera_bkg_button.setText(_translate("frog_dialog", "Camera"))
        self.dispersion_spinbox.setSuffix(_translate("frog_dialog", " nm/px"))
        self.camera_state_label.setText(_translate("frog_dialog", "UNKNOWN"))
        self.label_15.setText(_translate("frog_dialog", "Use bkg subtraction"))
        self.label_17.setText(_translate("frog_dialog", "Grab background"))
        self.camera_name_lineedit.setText(_translate("frog_dialog", "gunlaser/cameras/basler_test01"))
        self.label_16.setText(_translate("frog_dialog", "Threshold"))
        self.camera_framecounter_label.setText(_translate("frog_dialog", "--"))
        self.load_button.setText(_translate("frog_dialog", "Load"))
        self.load_filename_label.setText(_translate("frog_dialog", "--"))
        self.camera_gain_label.setText(_translate("frog_dialog", "--"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frog_dialog", "Image"))
        self.status_label.setText(_translate("frog_dialog", "Status"))
        self.primary_image_label.setText(_translate("frog_dialog", "--"))
        self.secondary_image_label.setText(_translate("frog_dialog", "--"))
        self.label_21.setText(_translate("frog_dialog", "Reconstructed temporal trace"))
        self.label_25.setText(_translate("frog_dialog", "Reconstructed spectral trace"))

from pyqtgraph import ImageView, PlotWidget
import frog_pcgp_res_rc
